/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JLinuxCopyMountProvider */

#ifndef _Included_JLinuxCopyMountProvider
#define _Included_JLinuxCopyMountProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JLinuxCopyMountProvider
 * Method:    createLinuxMountProvider
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_JLinuxCopyMountProvider_createLinuxMountProvider
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JLinuxCopyMountProvider
 * Method:    mountLinuxVolumeCopy
 * Signature: (JLJLinuxCopyMountConf;Ljava/lang/StringBuilder;)Z
 */
JNIEXPORT jboolean JNICALL Java_JLinuxCopyMountProvider_mountLinuxVolumeCopy
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     JLinuxCopyMountProvider
 * Method:    umountLinuxVolumeCopy
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_JLinuxCopyMountProvider_umountLinuxVolumeCopy
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     JLinuxCopyMountProvider
 * Method:    destroyLinuxMountProvider
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_JLinuxCopyMountProvider_destroyLinuxMountProvider
  (JNIEnv *, jobject, jlong);

/*
 * Class:     JLinuxCopyMountProvider
 * Method:    getLinuxMountProviderError
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JLinuxCopyMountProvider_getLinuxMountProviderError
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
